<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.1" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.1" />
    <ProjectReference Include="../../src/WindowsISOBuilder.Gui/WindowsISOBuilder.Gui.csproj" />
  </ItemGroup>
</Project>
