<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>WindowsISOBuilder</AssemblyName>
    <RootNamespace>WindowsISOBuilder.Gui</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.3.0.1</Version>
    <FileVersion>0.3.0.1</FileVersion>
    <AssemblyVersion>0.3.0.0</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
  </PropertyGroup>
</Project>
